/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fmaillet.orthocotation;

/**
 *
 * @author Fred
 */
public class BaseDatas extends javax.swing.JPanel {

    /**
     * Creates new form BaseDatas
     */
    public BaseDatas() {
        initComponents();
        jPhoriePStateChanged (null) ;
        jPhorieLStateChanged (null) ;
        jFusionDPStateChanged (null) ;
        jFusionCPStateChanged (null) ;
        jFusionDLStateChanged (null) ;
        jFusionCLStateChanged (null) ;
        jPPAStateChanged (null) ;
        jPPCStateChanged (null) ;
        
        //Unités
        jUnit1.setText("\u0394");jUnit2.setText("\u0394");jUnit3.setText("\u0394");jUnit4.setText("\u0394");
        jUnit5.setText("\u0394");jUnit6.setText("\u0394");jUnit7.setText("\u0394");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPhorieL = new javax.swing.JSpinner();
        jPhorieP = new javax.swing.JSpinner();
        jPhorieLds = new javax.swing.JLabel();
        jPhoriePds = new javax.swing.JLabel();
        jCheckPhorieL = new javax.swing.JCheckBox();
        jCheckPhorieP = new javax.swing.JCheckBox();
        jCheckFusionDP = new javax.swing.JCheckBox();
        jFusionDP = new javax.swing.JSpinner();
        jFusionDPds = new javax.swing.JLabel();
        jCheckFusionCP = new javax.swing.JCheckBox();
        jFusionCP = new javax.swing.JSpinner();
        jFusionCPds = new javax.swing.JLabel();
        jCheckFusionDL = new javax.swing.JCheckBox();
        jFusionDL = new javax.swing.JSpinner();
        jFusionDLds = new javax.swing.JLabel();
        jCheckFusionCL = new javax.swing.JCheckBox();
        jFusionCL = new javax.swing.JSpinner();
        jFusionCLds = new javax.swing.JLabel();
        jPPC = new javax.swing.JSpinner();
        jPPA = new javax.swing.JSpinner();
        jPPCds = new javax.swing.JLabel();
        jPPAds = new javax.swing.JLabel();
        jCheckPPC = new javax.swing.JCheckBox();
        jCheckPPA = new javax.swing.JCheckBox();
        jUnit1 = new javax.swing.JLabel();
        jUnit2 = new javax.swing.JLabel();
        jUnit3 = new javax.swing.JLabel();
        jUnit4 = new javax.swing.JLabel();
        jUnit5 = new javax.swing.JLabel();
        jUnit6 = new javax.swing.JLabel();
        jUnit7 = new javax.swing.JLabel();
        jUnit8 = new javax.swing.JLabel();

        jPhorieL.setModel(new javax.swing.SpinnerNumberModel(-1, null, null, 1));
        jPhorieL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jPhorieLStateChanged(evt);
            }
        });
        jPhorieL.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPhorieLPropertyChange(evt);
            }
        });

        jPhorieP.setModel(new javax.swing.SpinnerNumberModel(-3, null, null, 1));
        jPhorieP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jPhoriePStateChanged(evt);
            }
        });

        jPhorieLds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPhorieLds.setForeground(java.awt.Color.red);
        jPhorieLds.setText("...");

        jPhoriePds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPhoriePds.setForeground(java.awt.Color.red);
        jPhoriePds.setText("...");

        jCheckPhorieL.setSelected(true);
        jCheckPhorieL.setText("Phorie (L) :");
        jCheckPhorieL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckPhorieLStateChanged(evt);
            }
        });

        jCheckPhorieP.setSelected(true);
        jCheckPhorieP.setText("Phorie (P) :");
        jCheckPhorieP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckPhoriePStateChanged(evt);
            }
        });

        jCheckFusionDP.setSelected(true);
        jCheckFusionDP.setText("D' :");
        jCheckFusionDP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckFusionDPStateChanged(evt);
            }
        });

        jFusionDP.setModel(new javax.swing.SpinnerNumberModel(12, null, null, 1));
        jFusionDP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jFusionDPStateChanged(evt);
            }
        });

        jFusionDPds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFusionDPds.setForeground(java.awt.Color.red);
        jFusionDPds.setText("...");

        jCheckFusionCP.setSelected(true);
        jCheckFusionCP.setText("C' :");
        jCheckFusionCP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckFusionCPStateChanged(evt);
            }
        });

        jFusionCP.setModel(new javax.swing.SpinnerNumberModel(23, null, null, 1));
        jFusionCP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jFusionCPStateChanged(evt);
            }
        });

        jFusionCPds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFusionCPds.setForeground(java.awt.Color.red);
        jFusionCPds.setText("...");

        jCheckFusionDL.setSelected(true);
        jCheckFusionDL.setText("D :");
        jCheckFusionDL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckFusionDLStateChanged(evt);
            }
        });

        jFusionDL.setModel(new javax.swing.SpinnerNumberModel(7, null, null, 1));
        jFusionDL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jFusionDLStateChanged(evt);
            }
        });

        jFusionDLds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFusionDLds.setForeground(java.awt.Color.red);
        jFusionDLds.setText("...");

        jCheckFusionCL.setSelected(true);
        jCheckFusionCL.setText("C :");
        jCheckFusionCL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckFusionCLStateChanged(evt);
            }
        });
        jCheckFusionCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckFusionCLActionPerformed(evt);
            }
        });

        jFusionCL.setModel(new javax.swing.SpinnerNumberModel(11, null, null, 1));
        jFusionCL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jFusionCLStateChanged(evt);
            }
        });

        jFusionCLds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFusionCLds.setForeground(java.awt.Color.red);
        jFusionCLds.setText("...");

        jPPC.setModel(new javax.swing.SpinnerNumberModel(2.5d, null, null, 0.5d));
        jPPC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jPPCStateChanged(evt);
            }
        });
        jPPC.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPPCPropertyChange(evt);
            }
        });

        jPPA.setModel(new javax.swing.SpinnerNumberModel(10.0d, 1.0d, null, 0.5d));
        jPPA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jPPAStateChanged(evt);
            }
        });

        jPPCds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPPCds.setForeground(java.awt.Color.red);
        jPPCds.setText("...");

        jPPAds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPPAds.setForeground(java.awt.Color.red);
        jPPAds.setText("...");

        jCheckPPC.setSelected(true);
        jCheckPPC.setText("PPC :");
        jCheckPPC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckPPCStateChanged(evt);
            }
        });

        jCheckPPA.setSelected(true);
        jCheckPPA.setText("PPA :");
        jCheckPPA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckPPAStateChanged(evt);
            }
        });

        jUnit1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jUnit1.setText("d");

        jUnit2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jUnit2.setText("d");

        jUnit3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jUnit3.setText("d");

        jUnit4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jUnit4.setText("d");

        jUnit5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jUnit5.setText("d");

        jUnit6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jUnit6.setText("d");

        jUnit7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jUnit7.setText("d");

        jUnit8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jUnit8.setText("d");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckPhorieP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPhorieP, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckPhorieL)
                            .addComponent(jCheckFusionDP)
                            .addComponent(jCheckFusionCP)
                            .addComponent(jCheckFusionCL)
                            .addComponent(jCheckFusionDL)
                            .addComponent(jCheckPPC)
                            .addComponent(jCheckPPA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPPA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPPC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPhorieL, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFusionDP, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFusionCP, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFusionCL, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFusionDL, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUnit3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUnit4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUnit5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUnit6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUnit7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPhoriePds, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPPCds, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPhorieLds, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFusionDPds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFusionCPds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFusionCLds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFusionDLds, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jUnit8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPPAds, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPhorieL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPhorieLds)
                    .addComponent(jCheckPhorieL)
                    .addComponent(jUnit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPhorieP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPhoriePds)
                    .addComponent(jCheckPhorieP)
                    .addComponent(jUnit3))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckFusionDP)
                    .addComponent(jFusionDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFusionDPds)
                    .addComponent(jUnit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckFusionCP)
                    .addComponent(jFusionCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFusionCPds)
                    .addComponent(jUnit4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckFusionCL)
                    .addComponent(jFusionCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFusionCLds)
                    .addComponent(jUnit5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckFusionDL)
                    .addComponent(jFusionDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFusionDLds)
                    .addComponent(jUnit6))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPPCds)
                    .addComponent(jCheckPPC)
                    .addComponent(jUnit7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPPAds)
                    .addComponent(jCheckPPA)
                    .addComponent(jUnit8))
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPhorieLPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPhorieLPropertyChange
        
    }//GEN-LAST:event_jPhorieLPropertyChange

    private void jPhorieLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jPhorieLStateChanged
        int p = (int) jPhorieL.getValue() ;

        double ds = OrthoCotation.baseValues.updatePhorieL ( p, jCheckPhorieL.isSelected() ) ;
        jPhorieLds.setText(String.format("%+.2f", ds) + " DS");
    }//GEN-LAST:event_jPhorieLStateChanged

    private void jPhoriePStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jPhoriePStateChanged
        int p = (int) jPhorieP.getValue() ;
        double ds = OrthoCotation.baseValues.updatePhorieP ( p, jCheckPhorieP.isSelected() ) ;
        jPhoriePds.setText(String.format("%+.2f", ds) + " DS");
    }//GEN-LAST:event_jPhoriePStateChanged

    private void jCheckPhorieLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckPhorieLStateChanged
        jPhorieLStateChanged (null) ;
    }//GEN-LAST:event_jCheckPhorieLStateChanged

    private void jCheckPhoriePStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckPhoriePStateChanged
        jPhoriePStateChanged (null) ;
    }//GEN-LAST:event_jCheckPhoriePStateChanged

    private void jCheckFusionDPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckFusionDPStateChanged
        jFusionDPStateChanged (null) ;
    }//GEN-LAST:event_jCheckFusionDPStateChanged

    private void jFusionDPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jFusionDPStateChanged
        int p = (int) jFusionDP.getValue() ;
        double ds = OrthoCotation.baseValues.updateFusionDP ( p, jCheckFusionDP.isSelected() ) ;
        jFusionDPds.setText(String.format("%+.2f", ds) + " DS");
    }//GEN-LAST:event_jFusionDPStateChanged

    private void jCheckFusionCPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckFusionCPStateChanged
        jFusionCPStateChanged (null) ;
    }//GEN-LAST:event_jCheckFusionCPStateChanged

    private void jFusionCPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jFusionCPStateChanged
        int p = (int) jFusionCP.getValue() ;
        double ds = OrthoCotation.baseValues.updateFusionCP ( p, jCheckFusionCP.isSelected() ) ;
        jFusionCPds.setText(String.format("%+.2f", ds) + " DS");
    }//GEN-LAST:event_jFusionCPStateChanged

    private void jCheckFusionDLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckFusionDLStateChanged
        jFusionDLStateChanged (null) ;
    }//GEN-LAST:event_jCheckFusionDLStateChanged

    private void jFusionDLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jFusionDLStateChanged
        int p = (int) jFusionDL.getValue() ;
        double ds = OrthoCotation.baseValues.updateFusionDL ( p, jCheckFusionDL.isSelected() ) ;
        jFusionDLds.setText(String.format("%+.2f", ds) + " DS");
    }//GEN-LAST:event_jFusionDLStateChanged

    private void jCheckFusionCLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckFusionCLStateChanged
        jFusionCLStateChanged (null) ;
    }//GEN-LAST:event_jCheckFusionCLStateChanged

    private void jFusionCLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jFusionCLStateChanged
        int p = (int) jFusionCL.getValue() ;
        double ds = OrthoCotation.baseValues.updateFusionCL ( p, jCheckFusionCL.isSelected() ) ;
        jFusionCLds.setText(String.format("%+.2f", ds) + " DS");
    }//GEN-LAST:event_jFusionCLStateChanged

    private void jCheckFusionCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckFusionCLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckFusionCLActionPerformed

    private void jPPCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jPPCStateChanged
        double p = (double) jPPC.getValue() ;
        double ds = OrthoCotation.baseValues.updatePPC ( p, jCheckPPC.isSelected() ) ;
        jPPCds.setText(String.format("%+.2f", ds) + " DS");
    }//GEN-LAST:event_jPPCStateChanged

    private void jPPCPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPPCPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPPCPropertyChange

    public void updateFromAge () {
        jPPAStateChanged (null) ;
        jCheckPPA.setSelected(true) ;
    }
    
    private void jPPAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jPPAStateChanged
        double p = (double) jPPA.getValue() ;
        p = 100 / p ;
        double ds = OrthoCotation.baseValues.updatePPA ( p, jCheckPPA.isSelected() ) ;
        jUnit8.setText ("cm (soit " + String.format("%+.2f", p) + " \u03B4)") ;
        if (OrthoCotation.baseValues.patientAge.years != 0)
            jPPAds.setText(String.format("%+.2f", ds) + " DS");
        else {
            jPPAds.setText("...") ;
            jCheckPPA.setSelected(false) ;
        }
    }//GEN-LAST:event_jPPAStateChanged

    private void jCheckPPCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckPPCStateChanged
        jPPCStateChanged (null) ;
    }//GEN-LAST:event_jCheckPPCStateChanged

    private void jCheckPPAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckPPAStateChanged
        jPPAStateChanged (null) ;
    }//GEN-LAST:event_jCheckPPAStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckFusionCL;
    private javax.swing.JCheckBox jCheckFusionCP;
    private javax.swing.JCheckBox jCheckFusionDL;
    private javax.swing.JCheckBox jCheckFusionDP;
    private javax.swing.JCheckBox jCheckPPA;
    private javax.swing.JCheckBox jCheckPPC;
    private javax.swing.JCheckBox jCheckPhorieL;
    private javax.swing.JCheckBox jCheckPhorieP;
    private javax.swing.JSpinner jFusionCL;
    private javax.swing.JLabel jFusionCLds;
    private javax.swing.JSpinner jFusionCP;
    private javax.swing.JLabel jFusionCPds;
    private javax.swing.JSpinner jFusionDL;
    private javax.swing.JLabel jFusionDLds;
    private javax.swing.JSpinner jFusionDP;
    private javax.swing.JLabel jFusionDPds;
    private javax.swing.JSpinner jPPA;
    private javax.swing.JLabel jPPAds;
    private javax.swing.JSpinner jPPC;
    private javax.swing.JLabel jPPCds;
    private javax.swing.JSpinner jPhorieL;
    private javax.swing.JLabel jPhorieLds;
    private javax.swing.JSpinner jPhorieP;
    private javax.swing.JLabel jPhoriePds;
    private javax.swing.JLabel jUnit1;
    private javax.swing.JLabel jUnit2;
    private javax.swing.JLabel jUnit3;
    private javax.swing.JLabel jUnit4;
    private javax.swing.JLabel jUnit5;
    private javax.swing.JLabel jUnit6;
    private javax.swing.JLabel jUnit7;
    private javax.swing.JLabel jUnit8;
    // End of variables declaration//GEN-END:variables
}
