/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fmaillet.orthocotation;

/**
 *
 * @author Fred
 */
public class BaseDatas extends javax.swing.JPanel {

    /**
     * Creates new form BaseDatas
     */
    public BaseDatas() {
        initComponents();
        jPhoriePStateChanged (null) ;
        jPhorieLStateChanged (null) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPhorieP = new javax.swing.JSpinner();
        jPhorieL = new javax.swing.JSpinner();
        jPhoriePds = new javax.swing.JLabel();
        jPhorieLds = new javax.swing.JLabel();
        jCheckPhorieP = new javax.swing.JCheckBox();
        jCheckPhorieP1 = new javax.swing.JCheckBox();

        jPhorieP.setModel(new javax.swing.SpinnerNumberModel());
        jPhorieP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jPhoriePStateChanged(evt);
            }
        });
        jPhorieP.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPhoriePPropertyChange(evt);
            }
        });

        jPhorieL.setModel(new javax.swing.SpinnerNumberModel());
        jPhorieL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jPhorieLStateChanged(evt);
            }
        });

        jPhoriePds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPhoriePds.setForeground(java.awt.Color.red);
        jPhoriePds.setText("...");

        jPhorieLds.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPhorieLds.setForeground(java.awt.Color.red);
        jPhorieLds.setText("...");

        jCheckPhorieP.setText("Phorie (P) :");
        jCheckPhorieP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckPhoriePActionPerformed(evt);
            }
        });

        jCheckPhorieP1.setText("Phorie (L) :");
        jCheckPhorieP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckPhorieP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckPhorieP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPhorieL, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPhorieLds, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckPhorieP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPhorieP, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPhoriePds, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPhorieP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPhoriePds)
                    .addComponent(jCheckPhorieP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPhorieL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPhorieLds)
                    .addComponent(jCheckPhorieP1))
                .addContainerGap(386, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPhoriePPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPhoriePPropertyChange
        
    }//GEN-LAST:event_jPhoriePPropertyChange

    private void jPhoriePStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jPhoriePStateChanged
        int p = (int) jPhorieP.getValue() ;
        double ds = - Math.abs((double) p + 3.0 ) / 3.0 ;
        jPhoriePds.setText(String.format("%+.2f", ds) + " DS");
    }//GEN-LAST:event_jPhoriePStateChanged

    private void jPhorieLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jPhorieLStateChanged
        int p = (int) jPhorieL.getValue() ;
        double ds = - Math.abs((double) p + 3.0 ) / 3.0 ;
        jPhorieLds.setText(String.format("%+.2f", ds) + " DS");
    }//GEN-LAST:event_jPhorieLStateChanged

    private void jCheckPhoriePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckPhoriePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckPhoriePActionPerformed

    private void jCheckPhorieP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckPhorieP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckPhorieP1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckPhorieP;
    private javax.swing.JCheckBox jCheckPhorieP1;
    private javax.swing.JSpinner jPhorieL;
    private javax.swing.JLabel jPhorieLds;
    private javax.swing.JSpinner jPhorieP;
    private javax.swing.JLabel jPhoriePds;
    // End of variables declaration//GEN-END:variables
}
