/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fmaillet.orthocotation;

import javax.swing.text.Document;

/**
 *
 * @author Fred
 */
public class Criterium_JDialog extends javax.swing.JDialog {

    /**
     * Creates new form VB_JDialog
     */
    public Criterium_JDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        String HTMLTEXT = "<html><h3>Critère de Sheard :</h3><hr>"
                + "<blockquote>Afin d'évaluer l'effort qui pèse sur le système de fusion en fonction "
                + "de la phorie, Sheard a proposé que la réserve fusionnelle devait être au moins "
                + "égale au double de la phorie. Ainsi, en cas d'exophorie, le sujet doit disposer du "
                + "double de convergence; en cas d'ésophorie, le sujet doit disposer du double de divergence.<br>"
                + "Le critère de Sheard permet d'évaluer l'effort de rééducation pour augmenter la réserve"
                + " ou le prisme nécessaire pour diminuer la demande.<br><br>"
                + "<b>Exemples :</b><br>"
                + "(VL) : un sujet présente E6 D6. Le critère de Sheard n'est pas rempli puisqu'il lui faudrait "
                + "au moins D12 pour compenser confortablement son ésophorie.<br>"
                + "(VL) : un sujet présente E2 D4. Selon Sheard, le sujet dispose d'une réserve fusionnelle "
                + "susceptible de lui permettre de compenser son ésophorie.<br>"
                + "(VP) : un sujet présente X'17 C'15. Le sujet manque de (17x2)-15=9 dioptries d'amplitude de fusion en "
                + "convergence pour compenser confortable son exophorie.<br>"
                + "<br><br>"
                + "Un certain nombre d'études ont confirmé le rôle prédictif du critère de Sheard : il est à la fois bien "
                + "corrélé aux symptômes et à leur amélioration après augmentation des réserves fusionnelles."
                + "</blockquote>"
                + ""
                + "<br><br><i>(à suivre...)</i></html>";
        
        //Texte
        jTextPane.setContentType("text/html");
        jTextPane.setText(HTMLTEXT);
        jTextPane.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setText("Aide saisie \"Vision Binoculaire\"");

        jTextPane.setText("hello");
        jScrollPane2.setViewportView(jTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))
                        .addGap(0, 573, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose () ;
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane;
    // End of variables declaration//GEN-END:variables
}
