/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fmaillet.orthocotation;

/**
 *
 * @author Fred
 */
public class Panel_Optic extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Optic
     */
    public Panel_Optic() {
        initComponents();
    }
    
    private void transpose1 () {
        int angle = (Integer) jAngle_1.getValue() ;
        jAngle_2.setValue( (angle +90 ) % 180 );
        
        double astig = (double) jAstigmatisme_1.getValue() ;
        jAstigmatisme_2.setValue( - astig  );
        
        double sphere = (double) jSphere_1.getValue() ;
        //double astig = (double) jAstigmatisme_1.getValue() ;
        jSphere_2.setValue( sphere + astig  );
    }
    
    private void transpose2 () {
        int angle = (Integer) jAngle_2.getValue() ;
        jAngle_1.setValue( (angle +90 ) % 180 );
        
        double astig = (double) jAstigmatisme_2.getValue() ;
        jAstigmatisme_1.setValue( - astig  );
        
        double sphere = (double) jSphere_2.getValue() ;
        //double astig = (double) jAstigmatisme_1.getValue() ;
        jSphere_1.setValue( sphere + astig  );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSphere_1 = new javax.swing.JSpinner();
        jAstigmatisme_1 = new javax.swing.JSpinner();
        jAngle_1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSphere_2 = new javax.swing.JSpinner();
        jAstigmatisme_2 = new javax.swing.JSpinner();
        jAngle_2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.gray);
        jLabel15.setText("Verres");

        jSphere_1.setModel(new javax.swing.SpinnerNumberModel(-1.25d, null, null, 0.25d));
        jSphere_1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSphere_1StateChanged(evt);
            }
        });

        jAstigmatisme_1.setModel(new javax.swing.SpinnerNumberModel(0.25d, null, null, 0.25d));
        jAstigmatisme_1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAstigmatisme_1StateChanged(evt);
            }
        });

        jAngle_1.setModel(new javax.swing.SpinnerNumberModel(10, 0, 360, 1));
        jAngle_1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAngle_1StateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("(");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("°  )");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("à");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("°  )");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("à");

        jSphere_2.setModel(new javax.swing.SpinnerNumberModel(-1.0d, null, null, 0.25d));
        jSphere_2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSphere_2StateChanged(evt);
            }
        });

        jAstigmatisme_2.setModel(new javax.swing.SpinnerNumberModel(-0.25d, null, null, 0.25d));
        jAstigmatisme_2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAstigmatisme_2StateChanged(evt);
            }
        });

        jAngle_2.setModel(new javax.swing.SpinnerNumberModel(100, 0, 360, 1));
        jAngle_2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAngle_2StateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("(");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSphere_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAstigmatisme_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAngle_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jSphere_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAstigmatisme_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAngle_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(127, 127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSphere_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAstigmatisme_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAngle_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSphere_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAstigmatisme_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAngle_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //On sauve 1
        int angle = (Integer) jAngle_1.getValue() ;
        double astig = (double) jAstigmatisme_1.getValue() ;
        double sphere = (double) jSphere_1.getValue() ;
        //On écrit 2 sur 1
        jAngle_1.setValue( (Integer) jAngle_2.getValue() );
        jAstigmatisme_1.setValue( (double) jAstigmatisme_2.getValue()  );
        jSphere_1.setValue( (double) jSphere_2.getValue()  );
        //On écrit 1 sur 2
        jAngle_2.setValue( angle );
        jAstigmatisme_2.setValue( astig );
        jSphere_2.setValue( sphere  );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jAngle_1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAngle_1StateChanged
        transpose1 () ;

    }//GEN-LAST:event_jAngle_1StateChanged

    private void jAstigmatisme_1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAstigmatisme_1StateChanged
        transpose1 () ;
    }//GEN-LAST:event_jAstigmatisme_1StateChanged

    private void jSphere_1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSphere_1StateChanged
        transpose1 () ;
    }//GEN-LAST:event_jSphere_1StateChanged

    private void jSphere_2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSphere_2StateChanged
        transpose2 () ;
    }//GEN-LAST:event_jSphere_2StateChanged

    private void jAstigmatisme_2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAstigmatisme_2StateChanged
        transpose2 () ;
    }//GEN-LAST:event_jAstigmatisme_2StateChanged

    private void jAngle_2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAngle_2StateChanged
        transpose2 () ;
    }//GEN-LAST:event_jAngle_2StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner jAngle_1;
    private javax.swing.JSpinner jAngle_2;
    private javax.swing.JSpinner jAstigmatisme_1;
    private javax.swing.JSpinner jAstigmatisme_2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSphere_1;
    private javax.swing.JSpinner jSphere_2;
    // End of variables declaration//GEN-END:variables
}
