package com.fmaillet.orthocotation;

import com.fmaillet.orthocotation.ColorChooserButton.ColorChangedListener;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import org.apache.commons.math3.distribution.NormalDistribution;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fred
 */
public class Panel_NEURO extends javax.swing.JPanel {

    public static int tvpsStdValues[] = new int[7] ;
    public static int tvpsPctlValues[] = new int[7] ;
    static public ColorChooserButton jChgeColor ;
    
    double thr_mean[]  = {15.66, 18.93, 20.71, 25.71, 26.69, 26.85, 28.75, 30.59, 35.25, 37.56, 38.39, 36.77};
    double thr_et[]  = {5.49, 6.11, 5.95, 5.71, 6.91, 7.32, 7.37, 7.23, 8.32, 7.78, 7.58, 8.19 };
    
    /**
     * Creates new form Panel_TVPS
     */
    public Panel_NEURO() {
        initComponents();
        
        

        //Positions
        
        
        updateThurstoneFI () ;
        updateBentonJLO () ;
    }
    
    public static double zScoreToPercentile(double zScore) {
		double percentile = 0;
		
		NormalDistribution dist = new NormalDistribution();
		percentile = dist.cumulativeProbability(zScore) * 100;
		return percentile;
    }
    
    
    
    public void updateThurstoneFI () {
        //if connected and correct age range
        if (OrthoCotation.user.nom == null) return ;
        if (OrthoCotation.baseValues.patientAge.years == 0) return ;
        //Age index
        jMsgThurstone.setText("");
        int y = OrthoCotation.baseValues.patientAge.years - 6;
        if (y<0) {y = 0 ; jMsgThurstone.setText("(Normes 6 ans par défaut)"); }
        else if (y>11) {y = 11 ; jMsgThurstone.setText("(Normes 14 ans par défaut)"); }
        
        //Ecart à la norme
        int v  = (int) jThurstone.getValue() ;
        double t  = ( (double) v - thr_mean[y]) / thr_et[y] ;
        jThurstone_DS.setText(String.format("%.2f", t));
    }
    
    public void updateBentonJLO () {
        //if connected and correct age range
        if (OrthoCotation.user.nom == null) return ;
        if (OrthoCotation.baseValues.patientAge.years == 0) return ;
        //Age index
        jMsgJLO.setText("");
        int y = OrthoCotation.baseValues.patientAge.years - 6;
        if (y<0) {y = 0 ; jMsgJLO.setText("(Normes 6 ans par défaut)"); }
        else if (y>11) {y = 11 ; jMsgJLO.setText("(Normes 14 ans par défaut)"); }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jMsgThurstone = new javax.swing.JLabel();
        jThurstone = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        jThurstone_DS = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jBentonJLO = new javax.swing.JSpinner();
        jBentonJLO_DS = new javax.swing.JLabel();
        jMsgJLO = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.gray);
        jLabel15.setText("Thurstone (FI)");

        jMsgThurstone.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jMsgThurstone.setForeground(java.awt.Color.red);
        jMsgThurstone.setText("(Pas de calculs en mode démo)");

        jThurstone.setModel(new javax.swing.SpinnerNumberModel(20, 0, 60, 1));
        jThurstone.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jThurstoneStateChanged(evt);
            }
        });

        jThurstone_DS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jThurstone_DS.setForeground(java.awt.Color.red);
        jThurstone_DS.setText("...");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.gray);
        jLabel16.setText("Benton (JLO)");

        jBentonJLO.setModel(new javax.swing.SpinnerNumberModel(20, 0, 30, 1));
        jBentonJLO.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jBentonJLOStateChanged(evt);
            }
        });

        jBentonJLO_DS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBentonJLO_DS.setForeground(java.awt.Color.red);
        jBentonJLO_DS.setText("...");

        jMsgJLO.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jMsgJLO.setForeground(java.awt.Color.red);
        jMsgJLO.setText("(Pas de calculs en mode démo)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMsgThurstone, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jThurstone, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jThurstone_DS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jMsgJLO, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jBentonJLO, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBentonJLO_DS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jMsgThurstone))
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jThurstone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jThurstone_DS))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jMsgJLO))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBentonJLO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBentonJLO_DS))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jThurstoneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jThurstoneStateChanged
        updateThurstoneFI () ;
    }//GEN-LAST:event_jThurstoneStateChanged

    private void jBentonJLOStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jBentonJLOStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jBentonJLOStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner jBentonJLO;
    private javax.swing.JLabel jBentonJLO_DS;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jMsgJLO;
    public static javax.swing.JLabel jMsgThurstone;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jThurstone;
    private javax.swing.JLabel jThurstone_DS;
    // End of variables declaration//GEN-END:variables
}

