/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fmaillet.orthocotation;

import javax.swing.text.Document;

/**
 *
 * @author Fred
 */
public class VB_JDialog extends javax.swing.JDialog {

    /**
     * Creates new form VB_JDialog
     */
    public VB_JDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        String HTMLTEXT = "<html><h3>Phories :</h3><hr>"
                + "<blockquote>Les exophories sont notées négativement, les ésophories positivement.<br>"
                + "Exemple : <b>X'8</b> sera saisi <b>-8</b>, et <b>E'3</b> sera saisi <b>+3</b>.</blockquote>"
                + "<h3>Amplitudes de fusion</h3><hr><blockquote>Elles sont notées directement, sans signe.<br>"
                + "Exemple <b>D'12</b> ou <b>C'12</b> seront saisis <b>12</b> dans les deux cas.<br>"
                + "Mesure recommandée sur cible accommodative et d'en retenir la valeur de flou,<br>"
                + "bien qu'à la barre de prisme elle soit plus difficile à différencier de la valeur de bris (diplopie).</blockquote>"
                + "<h3>PPC</h3><hr><blockquote>Il est rapporté en cm. Il est recommandé sur cible accommodative et de le<br>"
                + "répéter trois fois pour ne retenir que la dernière valeur afin de rendre compte de la fatigabilité.</blockquote>"
                + "<h3>PPA</h3><hr><blockquote>Il est rapporté en cm. L'application calcule l'amplitude accommodative correspondante<br>"
                + "et la valeur attendue en fonction de l'âge pour permettre l'évaluation de l'écart à la norme.<br>"
                + "Bien qu'il puisse être mesuré en monoculaire et en binoculaire, une seule mesure<br>"
                + "synthétique est reportée ici afin de ne pas alourdir le schéma.</blockquote>"
                + "<br><br><i>(à suivre...)</i></html>";
        
        //Texte
        jTextPane.setContentType("text/html");
        jTextPane.setText(HTMLTEXT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setText("Aide saisie \"Vision Binoculaire\"");

        jTextPane.setText("hello");
        jScrollPane2.setViewportView(jTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))
                        .addGap(0, 324, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose () ;
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane;
    // End of variables declaration//GEN-END:variables
}
